"""Hapus unique constraint dari kode_setor

Revision ID: e6dc8e98ffc3
Revises: 
Create Date: 2025-06-26 12:36:06.063447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6dc8e98ffc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokumen_pajak')
    with op.batch_alter_table('bukti_setor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bukti_setor_kode_setor_key'), type_='unique')

    with op.batch_alter_table('ppn_keluaran', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ppn_masukan', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppn_masukan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ppn_keluaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('bukti_setor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('bukti_setor_kode_setor_key'), ['kode_setor'], postgresql_nulls_not_distinct=False)

    op.create_table('dokumen_pajak',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dpp', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ppn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dokumen_pajak_pkey'))
    )
    # ### end Alembic commands ###
